name: RecordingAssistant
version: '${project.version}'
main: net.colsika.mochidsuki.recordingassistant.RecordingAssistant
api-version: 1.19

softdepend: [ ProtocolLib ]

commands:
  ra:
    aliases: [RecordingAssistant]
    description: ゲームのラウンド進行状況
    permission: RecordingAssistant.command.main
    permission-message: Permission denied
    usage: Banana
  timer:
    aliases: [ti]
    description: タイマー
    permission: RecordingAssistant.command.timer
    permission-message: Permission denied
    usage: Banana
