#撮影補佐プログラム(Recording Assistant Plugin)
#created by Mochidsuki
#権利についてはこちらをご覧ください -> https://github.com/MochidsukiC/RecordingAssistant/blob/master/README.md

#ピン機能
Pin:
  #ピン機能をを有効にするかどうか
  Enable_Pin: false
  #ピンを指すアイテムを指定。
  Pin_item: FILLED_MAP
